### ISSUE TITLE
05accuracy error message

### ISSUE THREAD

**Issue by vyelnats** [kyle-woodward/kaza-lc#5]
/Users/vic/opt/anaconda3/envs/gee/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

  _warn_prf(average, modifier, msg_start, len(result))

05accuracy.py:122: RuntimeWarning: invalid value encountered in long_scalars

  omission = (false_neg / (false_neg + true_pos))

05accuracy.py:123: RuntimeWarning: invalid value encountered in long_scalars

  comission = (false_pos / (false_neg + true_pos))

 

File "05accuracy.py", line 143, in <module>

    cm_df = pd.DataFrame(cm, columns = lc_dct.values(), index = lc_dct.values())

  File "/Users/vic/opt/anaconda3/envs/gee/lib/python3.8/site-packages/pandas/core/frame.py", line 720, in __init__

    mgr = ndarray_to_mgr(

  File "/Users/vic/opt/anaconda3/envs/gee/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 349, in ndarray_to_mgr

    _check_values_indices_shape_match(values, index, columns)

  File "/Users/vic/opt/anaconda3/envs/gee/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 420, in _check_values_indices_shape_match

    raise ValueError(f"Shape of passed values is {passed}, indices imply {implied}")

ValueError: Shape of passed values is (7, 7), indices imply (8, 8)

**Comment by kyle-woodward** [comment]
The ValueError indicates that the set of unique values for the 'LANDCOVER' property of the testing points and the 'classification' raster values from the Land Cover `ee.Image` do not match - which will produce a skewed and incorrect confusion matrix. The best solution would be some custom error handling in `05accuracy.py` explaining this in plain language, and presenting to the user the predicted and ground truth unique values that were passed from the land cover image and testing points respectively so that they can troubleshoot what they should do. 

Moreover, the mapping of each Landcover value (1) to its description (Built) should not be reliant on a static dictionary hard-coded into the script as it was done previously. This would prohibit the user from the flexibility of making land cover maps with different stratifications in the future without editing the script itself. Solutions would be: a) remove the value:label mapping altogether, and it is up to the user to check what label each land cover value corresponds to (not ideal) b) use a property in the testing points and/or the land cover `ee.Image` to map Landcover numeric values to their labels. This one is best but has ramifications for a few other scripts that are executed beforehand.

**Comment by kyle-woodward** [comment]
This has been addressed by the replacement of AREA2 tools for Accuracy Assessment and Area Estimation. Changes are reflected in `dev` branch.
